name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    name: Test Grok
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [linux, macos, windows]
        include:
          - build: linux
            os: ubuntu-latest
            rust: stable
          - build: macos
            os: macos-latest
            rust: stable
          - build: windows
            os: windows-latest
            rust: stable
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        name: Test with default features
        with:
          command: test
      - uses: actions-rs/cargo@v1
        name: Test with fancy-regex feature
        with:
          command: test
          args: --no-default-features --features fancy-regex
      - uses: actions-rs/cargo@v1
        name: Test with pcre2 feature
        with:
          command: test
          args: --no-default-features --features pcre2
      - uses: actions-rs/cargo@v1
        name: Test with onig feature
        with:
          command: test
          args: --no-default-features --features onig
      - uses: actions-rs/cargo@v1
        name: Test with regex feature
        with:
          command: test
          args: --no-default-features --features regex
